# Kafka Monitoring Stack for Docker Compose (Prometheus / Grafana)

image:https://img.shields.io/badge/License-Apache%202.0-blue.svg[https://github.com/streamthoughts/kafka-monitoring-stack-docker-compose/blob/master/LICENSE]
image:https://img.shields.io/github/issues-raw/streamthoughts/kafka-monitoring-stack-docker-compose[GitHub issues]
image:https://img.shields.io/github/stars/streamthoughts/kafka-monitoring-stack-docker-compose?style=social[GitHub Repo stars]

## Demonstration of using Prometheus and Grafana to monitor an Apache Kafka cluster

Reference project:
https://github.com/streamthoughts/kafka-monitoring-stack-docker-compose

---

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/crystalloide/kafka-monitoring-stack-docker-compose)

## Reminder

To display already instantiated Gitpod workspaces (useful for cleanup):
https://gitpod.io/workspaces

---

## Running this lab outside Gitpod (for example on your own VM)

### 1. Cloning the "Kafka Monitoring" repository

```bash
git clone https://github.com/streamthoughts/kafka-monitoring-stack-docker-compose.git
cd kafka-monitoring-stack-docker-compose
```

### Display current directory

```bash
pwd
```

---

## Available Full Stack

- Kafka (Confluent)
- Zookeeper
- Kafka Schema Registry (Confluent)
- KSQLDB
- Kafka Connect
- Prometheus
- Grafana
- AKHQ (https://akhq.io/)
- ZooNavigator (https://zoonavigator.elkozmon.com/en/stable/)

---

## Usage

```bash
./up -h
```

```text
--------------------------------------------------------------------------------
      ____        __           _____ __                            _
     / __ \____ _/ /_____ _   / ___// /_________  ____ _____ ___  (_)___  ____ _
    / / / / __ `/ __/ __ `/   \__ \/ __/ ___/ _ \/ __ `/ __ `__ \/ / __ \/ __ `/
   / /_/ / /_/ / /_/ /_/ /   ___/ / /_/ /  /  __/ /_/ / / / / / / / / / / /_/ /
  /_____/\__,_/\__/\__,_/   /____/\__/_/   \___/\__,_/_/ /_/ /_/_/_/ /_/\__, /
                                                                        /____/

 Powered by Apache Kafka!
--------------------------------------------------------------------------------
Usage: ./up [options]
     -n <[NAME]>        : Name of the stack to deploy (required)
     -s <[SERVICE]>     : Services to deploy (all if omitted)
     -h                 : Display this help

Available docker-compose stacks:

NAME                               | FILE
===================================+============================================
zk-kafka-multiple-nodes-sasl       | zk-kafka-multiple-nodes-sasl-stack.yml
zk-kafka-multiple-nodes            | zk-kafka-multiple-nodes-stack.yml
zk-kafka-single-node-full          | zk-kafka-single-node-full-stack.yml
zk-kafka-single-node-sasl          | zk-kafka-single-node-sasl-stack.yml
zk-kafka-single-node               | zk-kafka-single-node-stack.yml
zkless-kafka-multiple-nodes        | zkless-kafka-multiple-nodes-stack.yml
```

---

## Example

### Deploy a Kafka cluster (KRaft mode)

```bash
./up -n zkless-kafka-multiple-nodes
```

---

## 2. Start the desired Kafka / Confluent cluster

```bash
./up -n kraft-single-node-full
```

---

## 3. Topic Creation

Create the topic `demo-topic` with 6 partitions and 3 replicas:

```bash
docker exec -it kafka101 kafka-topics --create --partitions 6 --replication-factor 3 --topic demo-topic --bootstrap-server kafka101:29092
```

---

## 4. Message Production

Simulate producer activity:

```bash
docker exec -it kafka101 kafka-producer-perf-test --throughput 500 --num-records 100000000 --topic demo-topic --record-size 100 --producer-props bootstrap.servers=kafka101:29092
```

---

## 5. Message Consumption

Simulate consumer load:

```bash
docker exec -it kafka101 kafka-consumer-perf-test --messages 100000000 --timeout 1000000 --topic demo-topic --reporting-interval 1000 --show-detailed-stats --bootstrap-server kafka101:29092
```

---

## 6. Grafana Visualization

Open your browser and navigate to:

http://localhost:3000

Available dashboards:

- Kafka Cluster / Global Health Check
- Kafka Cluster / Performance
- Kafka Cluster / Zookeeper Connections
- Kafka Cluster / JVM & OS
- Kafka Cluster / Hard Disk Usage
- Kafka Cluster / Topic Logs

---

## Grafana Access

- URL: http://localhost:3000
- User: `admin`
- Password: `kafka`

---

## Prometheus Access

- URL: http://localhost:9090

---

## Contributions

Feedback, bug reports, and pull requests are welcome.

---

## Support

Please ⭐ star the repository to support the project.

---

## License

This project is licensed under the Apache License, Version 2.0.
